export const stories = [
  {
    profileImg: "/stories/profile-1.png",
    profileName: "Visual Artist",
    title: ["From unknown talent", "to a career built", "on your own terms"],
    linkLabel: "See the Journey",
    linkSrc: "/sample-project",
    storyImg: "/stories/story-1.jpg",
  },
  {
    profileImg: "/stories/profile-2.png",
    profileName: "Musician",
    title: ["Your first brand deal", "does not require", "a million followers"],
    linkLabel: "See the Journey",
    linkSrc: "/sample-project",
    storyImg: "/stories/story-2.jpg",
  },
  {
    profileImg: "/stories/profile-3.png",
    profileName: "Video Creator",
    title: ["Content that converts,", "audiences that stay,", "income that compounds"],
    linkLabel: "See the Journey",
    linkSrc: "/sample-project",
    storyImg: "/stories/story-3.jpg",
  },
  {
    profileImg: "/stories/profile-4.png",
    profileName: "Fashion Creator",
    title: ["Design your merch,", "launch your store,", "own your audience"],
    linkLabel: "See the Journey",
    linkSrc: "/sample-project",
    storyImg: "/stories/story-4.jpg",
  },
  {
    profileImg: "/stories/profile-2.png",
    profileName: "Podcaster",
    title: ["Build the audience", "that follows you", "anywhere you go"],
    linkLabel: "See the Journey",
    linkSrc: "/sample-project",
    storyImg: "/stories/story-5.jpg",
  },
  {
    profileImg: "/stories/profile-4.png",
    profileName: "Educator",
    title: ["Get discovered early,", "grow on your terms,", "earn what you deserve"],
    linkLabel: "See the Journey",
    linkSrc: "/sample-project",
    storyImg: "/stories/story-6.jpg",
  },
];
